# Generated by Django 4.2 on 2023-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dispic',
            field=models.TextField(default=0),
        ),
    ]
