# Generated by Django 4.2.2 on 2023-10-11 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_dispic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='BlogCommentcode',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Postcode',
        ),
    ]
