# Generated by Django 4.2.2 on 2023-10-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contactcode',
        ),
    ]
